version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: rollup
    versions:
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.3
    - 2.42.4
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
  - dependency-name: husky
    versions:
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typedoc
    versions:
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
  - dependency-name: ts-jest
    versions:
    - 26.5.2
    - 26.5.3
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: "@commitlint/config-angular"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.27
    - 14.14.29
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: eslint
    versions:
    - 7.19.0
